name: Rust

on:
  push:
    branches: [ "rust" ]
  pull_request:
    branches: [ "rust" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4
    - name: install alsa for rodio
      run: sudo apt-get update && sudo apt-get install --yes libasound2-dev pkg-config
    - name: Check formatting
      run: cargo fmt --all -- --check
    - name: Cargo check
      run: cargo check --workspace --all-targets
    - name: Build release binaries
      run: cargo build --release
    - name: Upload release artifact
      uses: actions/upload-artifact@v4
      with:
        name: deadlocked
        path: |
          target/release/deadlocked
          target/release/server
        if-no-files-found: error
